# Template für zentrale Konfiguration
user: pi
password: raspberry
ssh_authorized_keys:
  - "ssh-rsa AAAA..."
wifi:
  ssid: ""
  psk: ""
  country: "DE"
eth:
  static_ip: "192.168.1.100"
  netmask: "255.255.255.0"
  gateway: "192.168.1.1"
language: "de_DE.UTF-8"
timezone: "Europe/Berlin"
